package com.wk.wktransportation.entity;

public class CarInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.carnumber
     *
     * @mbg.generated
     */
    private String carnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.incubatornumber
     *
     * @mbg.generated
     */
    private String incubatornumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carinfo.rowno
     *
     * @mbg.generated
     */
    private Long rowno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.carnumber
     *
     * @return the value of carinfo.carnumber
     *
     * @mbg.generated
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.carnumber
     *
     * @param carnumber the value for carinfo.carnumber
     *
     * @mbg.generated
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.incubatornumber
     *
     * @return the value of carinfo.incubatornumber
     *
     * @mbg.generated
     */
    public String getIncubatornumber() {
        return incubatornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.incubatornumber
     *
     * @param incubatornumber the value for carinfo.incubatornumber
     *
     * @mbg.generated
     */
    public void setIncubatornumber(String incubatornumber) {
        this.incubatornumber = incubatornumber == null ? null : incubatornumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carinfo.rowno
     *
     * @return the value of carinfo.rowno
     *
     * @mbg.generated
     */
    public Long getRowno() {
        return rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carinfo.rowno
     *
     * @param rowno the value for carinfo.rowno
     *
     * @mbg.generated
     */
    public void setRowno(Long rowno) {
        this.rowno = rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CarInfo other = (CarInfo) that;
        return (this.getCarnumber() == null ? other.getCarnumber() == null : this.getCarnumber().equals(other.getCarnumber()))
            && (this.getIncubatornumber() == null ? other.getIncubatornumber() == null : this.getIncubatornumber().equals(other.getIncubatornumber()))
            && (this.getRowno() == null ? other.getRowno() == null : this.getRowno().equals(other.getRowno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCarnumber() == null) ? 0 : getCarnumber().hashCode());
        result = prime * result + ((getIncubatornumber() == null) ? 0 : getIncubatornumber().hashCode());
        result = prime * result + ((getRowno() == null) ? 0 : getRowno().hashCode());
        return result;
    }

}