package com.wk.wktransportation.entity;

public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.region
     *
     * @mbg.generated
     */
    private String region;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.salesman
     *
     * @mbg.generated
     */
    private String salesman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customerid1
     *
     * @mbg.generated
     */
    private String customerid1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.lis
     *
     * @mbg.generated
     */
    private String lis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.fax
     *
     * @mbg.generated
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.zipcode
     *
     * @mbg.generated
     */
    private String zipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.engineer
     *
     * @mbg.generated
     */
    private String engineer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.soft
     *
     * @mbg.generated
     */
    private String soft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.suoxie
     *
     * @mbg.generated
     */
    private String suoxie;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.hospitalname
     *
     * @mbg.generated
     */
    private String hospitalname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custid
     *
     * @mbg.generated
     */
    private String custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.rowno1
     *
     * @mbg.generated
     */
    private Long rowno1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.pinyin
     *
     * @mbg.generated
     */
    private String pinyin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.duty
     *
     * @mbg.generated
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.VIP
     *
     * @mbg.generated
     */
    private String vip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bednum
     *
     * @mbg.generated
     */
    private String bednum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customerid
     *
     * @mbg.generated
     */
    private String customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customername
     *
     * @mbg.generated
     */
    private String customername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact
     *
     * @return the value of customer.contact
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact
     *
     * @param contact the value for customer.contact
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.telephone
     *
     * @return the value of customer.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.telephone
     *
     * @param telephone the value for customer.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.city
     *
     * @return the value of customer.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.city
     *
     * @param city the value for customer.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.region
     *
     * @return the value of customer.region
     *
     * @mbg.generated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.region
     *
     * @param region the value for customer.region
     *
     * @mbg.generated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.salesman
     *
     * @return the value of customer.salesman
     *
     * @mbg.generated
     */
    public String getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.salesman
     *
     * @param salesman the value for customer.salesman
     *
     * @mbg.generated
     */
    public void setSalesman(String salesman) {
        this.salesman = salesman == null ? null : salesman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customerid1
     *
     * @return the value of customer.customerid1
     *
     * @mbg.generated
     */
    public String getCustomerid1() {
        return customerid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customerid1
     *
     * @param customerid1 the value for customer.customerid1
     *
     * @mbg.generated
     */
    public void setCustomerid1(String customerid1) {
        this.customerid1 = customerid1 == null ? null : customerid1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.lis
     *
     * @return the value of customer.lis
     *
     * @mbg.generated
     */
    public String getLis() {
        return lis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.lis
     *
     * @param lis the value for customer.lis
     *
     * @mbg.generated
     */
    public void setLis(String lis) {
        this.lis = lis == null ? null : lis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.fax
     *
     * @return the value of customer.fax
     *
     * @mbg.generated
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.fax
     *
     * @param fax the value for customer.fax
     *
     * @mbg.generated
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.zipcode
     *
     * @return the value of customer.zipcode
     *
     * @mbg.generated
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.zipcode
     *
     * @param zipcode the value for customer.zipcode
     *
     * @mbg.generated
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.engineer
     *
     * @return the value of customer.engineer
     *
     * @mbg.generated
     */
    public String getEngineer() {
        return engineer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.engineer
     *
     * @param engineer the value for customer.engineer
     *
     * @mbg.generated
     */
    public void setEngineer(String engineer) {
        this.engineer = engineer == null ? null : engineer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.soft
     *
     * @return the value of customer.soft
     *
     * @mbg.generated
     */
    public String getSoft() {
        return soft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.soft
     *
     * @param soft the value for customer.soft
     *
     * @mbg.generated
     */
    public void setSoft(String soft) {
        this.soft = soft == null ? null : soft.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.grade
     *
     * @return the value of customer.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.grade
     *
     * @param grade the value for customer.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.suoxie
     *
     * @return the value of customer.suoxie
     *
     * @mbg.generated
     */
    public String getSuoxie() {
        return suoxie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.suoxie
     *
     * @param suoxie the value for customer.suoxie
     *
     * @mbg.generated
     */
    public void setSuoxie(String suoxie) {
        this.suoxie = suoxie == null ? null : suoxie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.hospitalname
     *
     * @return the value of customer.hospitalname
     *
     * @mbg.generated
     */
    public String getHospitalname() {
        return hospitalname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.hospitalname
     *
     * @param hospitalname the value for customer.hospitalname
     *
     * @mbg.generated
     */
    public void setHospitalname(String hospitalname) {
        this.hospitalname = hospitalname == null ? null : hospitalname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custid
     *
     * @return the value of customer.custid
     *
     * @mbg.generated
     */
    public String getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custid
     *
     * @param custid the value for customer.custid
     *
     * @mbg.generated
     */
    public void setCustid(String custid) {
        this.custid = custid == null ? null : custid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.rowno1
     *
     * @return the value of customer.rowno1
     *
     * @mbg.generated
     */
    public Long getRowno1() {
        return rowno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.rowno1
     *
     * @param rowno1 the value for customer.rowno1
     *
     * @mbg.generated
     */
    public void setRowno1(Long rowno1) {
        this.rowno1 = rowno1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.pinyin
     *
     * @return the value of customer.pinyin
     *
     * @mbg.generated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.pinyin
     *
     * @param pinyin the value for customer.pinyin
     *
     * @mbg.generated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.duty
     *
     * @return the value of customer.duty
     *
     * @mbg.generated
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.duty
     *
     * @param duty the value for customer.duty
     *
     * @mbg.generated
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.VIP
     *
     * @return the value of customer.VIP
     *
     * @mbg.generated
     */
    public String getVip() {
        return vip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.VIP
     *
     * @param vip the value for customer.VIP
     *
     * @mbg.generated
     */
    public void setVip(String vip) {
        this.vip = vip == null ? null : vip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bednum
     *
     * @return the value of customer.bednum
     *
     * @mbg.generated
     */
    public String getBednum() {
        return bednum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bednum
     *
     * @param bednum the value for customer.bednum
     *
     * @mbg.generated
     */
    public void setBednum(String bednum) {
        this.bednum = bednum == null ? null : bednum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customerid
     *
     * @return the value of customer.customerid
     *
     * @mbg.generated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customerid
     *
     * @param customerid the value for customer.customerid
     *
     * @mbg.generated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customername
     *
     * @return the value of customer.customername
     *
     * @mbg.generated
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customername
     *
     * @param customername the value for customer.customername
     *
     * @mbg.generated
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Customer other = (Customer) that;
        return (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getRegion() == null ? other.getRegion() == null : this.getRegion().equals(other.getRegion()))
            && (this.getSalesman() == null ? other.getSalesman() == null : this.getSalesman().equals(other.getSalesman()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getCustomerid1() == null ? other.getCustomerid1() == null : this.getCustomerid1().equals(other.getCustomerid1()))
            && (this.getLis() == null ? other.getLis() == null : this.getLis().equals(other.getLis()))
            && (this.getFax() == null ? other.getFax() == null : this.getFax().equals(other.getFax()))
            && (this.getZipcode() == null ? other.getZipcode() == null : this.getZipcode().equals(other.getZipcode()))
            && (this.getEngineer() == null ? other.getEngineer() == null : this.getEngineer().equals(other.getEngineer()))
            && (this.getSoft() == null ? other.getSoft() == null : this.getSoft().equals(other.getSoft()))
            && (this.getGrade() == null ? other.getGrade() == null : this.getGrade().equals(other.getGrade()))
            && (this.getSuoxie() == null ? other.getSuoxie() == null : this.getSuoxie().equals(other.getSuoxie()))
            && (this.getHospitalname() == null ? other.getHospitalname() == null : this.getHospitalname().equals(other.getHospitalname()))
            && (this.getCustid() == null ? other.getCustid() == null : this.getCustid().equals(other.getCustid()))
            && (this.getRowno1() == null ? other.getRowno1() == null : this.getRowno1().equals(other.getRowno1()))
            && (this.getPinyin() == null ? other.getPinyin() == null : this.getPinyin().equals(other.getPinyin()))
            && (this.getDuty() == null ? other.getDuty() == null : this.getDuty().equals(other.getDuty()))
            && (this.getVip() == null ? other.getVip() == null : this.getVip().equals(other.getVip()))
            && (this.getBednum() == null ? other.getBednum() == null : this.getBednum().equals(other.getBednum()))
            && (this.getCustomerid() == null ? other.getCustomerid() == null : this.getCustomerid().equals(other.getCustomerid()))
            && (this.getCustomername() == null ? other.getCustomername() == null : this.getCustomername().equals(other.getCustomername()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getRegion() == null) ? 0 : getRegion().hashCode());
        result = prime * result + ((getSalesman() == null) ? 0 : getSalesman().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getCustomerid1() == null) ? 0 : getCustomerid1().hashCode());
        result = prime * result + ((getLis() == null) ? 0 : getLis().hashCode());
        result = prime * result + ((getFax() == null) ? 0 : getFax().hashCode());
        result = prime * result + ((getZipcode() == null) ? 0 : getZipcode().hashCode());
        result = prime * result + ((getEngineer() == null) ? 0 : getEngineer().hashCode());
        result = prime * result + ((getSoft() == null) ? 0 : getSoft().hashCode());
        result = prime * result + ((getGrade() == null) ? 0 : getGrade().hashCode());
        result = prime * result + ((getSuoxie() == null) ? 0 : getSuoxie().hashCode());
        result = prime * result + ((getHospitalname() == null) ? 0 : getHospitalname().hashCode());
        result = prime * result + ((getCustid() == null) ? 0 : getCustid().hashCode());
        result = prime * result + ((getRowno1() == null) ? 0 : getRowno1().hashCode());
        result = prime * result + ((getPinyin() == null) ? 0 : getPinyin().hashCode());
        result = prime * result + ((getDuty() == null) ? 0 : getDuty().hashCode());
        result = prime * result + ((getVip() == null) ? 0 : getVip().hashCode());
        result = prime * result + ((getBednum() == null) ? 0 : getBednum().hashCode());
        result = prime * result + ((getCustomerid() == null) ? 0 : getCustomerid().hashCode());
        result = prime * result + ((getCustomername() == null) ? 0 : getCustomername().hashCode());
        return result;
    }
}