package com.wk.wktransportation.entity;

import java.io.Serializable;

public class Tempertumer implements Serializable{
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempertumer.datetime
     *
     * @mbg.generated
     */
    private String datetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempertumer.incubatornumber
     *
     * @mbg.generated
     */
    private String incubatornumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempertumer.tempertumer
     *
     * @mbg.generated
     */
    private String tempertumer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempertumer.rowno
     *
     * @mbg.generated
     */
    private Long rowno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempertumer.tmperinfo
     *
     * @mbg.generated
     */
    private String tmperinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempertumer.datetime
     *
     * @return the value of tempertumer.datetime
     *
     * @mbg.generated
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempertumer.datetime
     *
     * @param datetime the value for tempertumer.datetime
     *
     * @mbg.generated
     */
    public void setDatetime(String datetime) {
        this.datetime = datetime == null ? null : datetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempertumer.incubatornumber
     *
     * @return the value of tempertumer.incubatornumber
     *
     * @mbg.generated
     */
    public String getIncubatornumber() {
        return incubatornumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempertumer.incubatornumber
     *
     * @param incubatornumber the value for tempertumer.incubatornumber
     *
     * @mbg.generated
     */
    public void setIncubatornumber(String incubatornumber) {
        this.incubatornumber = incubatornumber == null ? null : incubatornumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempertumer.tempertumer
     *
     * @return the value of tempertumer.tempertumer
     *
     * @mbg.generated
     */
    public String getTempertumer() {
        return tempertumer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempertumer.tempertumer
     *
     * @param tempertumer the value for tempertumer.tempertumer
     *
     * @mbg.generated
     */
    public void setTempertumer(String tempertumer) {
        this.tempertumer = tempertumer == null ? null : tempertumer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempertumer.rowno
     *
     * @return the value of tempertumer.rowno
     *
     * @mbg.generated
     */
    public Long getRowno() {
        return rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempertumer.rowno
     *
     * @param rowno the value for tempertumer.rowno
     *
     * @mbg.generated
     */
    public void setRowno(Long rowno) {
        this.rowno = rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempertumer.tmperinfo
     *
     * @return the value of tempertumer.tmperinfo
     *
     * @mbg.generated
     */
    public String getTmperinfo() {
        return tmperinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempertumer.tmperinfo
     *
     * @param tmperinfo the value for tempertumer.tmperinfo
     *
     * @mbg.generated
     */
    public void setTmperinfo(String tmperinfo) {
        this.tmperinfo = tmperinfo == null ? null : tmperinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempertumer
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Tempertumer other = (Tempertumer) that;
        return (this.getDatetime() == null ? other.getDatetime() == null : this.getDatetime().equals(other.getDatetime()))
            && (this.getIncubatornumber() == null ? other.getIncubatornumber() == null : this.getIncubatornumber().equals(other.getIncubatornumber()))
            && (this.getTempertumer() == null ? other.getTempertumer() == null : this.getTempertumer().equals(other.getTempertumer()))
            && (this.getRowno() == null ? other.getRowno() == null : this.getRowno().equals(other.getRowno()))
            && (this.getTmperinfo() == null ? other.getTmperinfo() == null : this.getTmperinfo().equals(other.getTmperinfo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempertumer
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDatetime() == null) ? 0 : getDatetime().hashCode());
        result = prime * result + ((getIncubatornumber() == null) ? 0 : getIncubatornumber().hashCode());
        result = prime * result + ((getTempertumer() == null) ? 0 : getTempertumer().hashCode());
        result = prime * result + ((getRowno() == null) ? 0 : getRowno().hashCode());
        result = prime * result + ((getTmperinfo() == null) ? 0 : getTmperinfo().hashCode());
        return result;
    }
}