package com.wk.wktransportation.entity;

public class TempBox {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempboxinfo.tempbox
     *
     * @mbg.generated
     */
    private String tempbox;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tempboxinfo.rowno
     *
     * @mbg.generated
     */
    private Long rowno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempboxinfo.tempbox
     *
     * @return the value of tempboxinfo.tempbox
     *
     * @mbg.generated
     */
    public String getTempbox() {
        return tempbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempboxinfo.tempbox
     *
     * @param tempbox the value for tempboxinfo.tempbox
     *
     * @mbg.generated
     */
    public void setTempbox(String tempbox) {
        this.tempbox = tempbox == null ? null : tempbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tempboxinfo.rowno
     *
     * @return the value of tempboxinfo.rowno
     *
     * @mbg.generated
     */
    public Long getRowno() {
        return rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tempboxinfo.rowno
     *
     * @param rowno the value for tempboxinfo.rowno
     *
     * @mbg.generated
     */
    public void setRowno(Long rowno) {
        this.rowno = rowno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempboxinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TempBox other = (TempBox) that;
        return (this.getTempbox() == null ? other.getTempbox() == null : this.getTempbox().equals(other.getTempbox()))
            && (this.getRowno() == null ? other.getRowno() == null : this.getRowno().equals(other.getRowno()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tempboxinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTempbox() == null) ? 0 : getTempbox().hashCode());
        result = prime * result + ((getRowno() == null) ? 0 : getRowno().hashCode());
        return result;
    }
}