package com.wk.wktransportation.entity;

public class Worker {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.worker
     *
     * @mbg.generated
     */
    private String worker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column worker.ronwo
     *
     * @mbg.generated
     */
    private Long ronwo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.worker
     *
     * @return the value of worker.worker
     *
     * @mbg.generated
     */
    public String getWorker() {
        return worker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.worker
     *
     * @param worker the value for worker.worker
     *
     * @mbg.generated
     */
    public void setWorker(String worker) {
        this.worker = worker == null ? null : worker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column worker.ronwo
     *
     * @return the value of worker.ronwo
     *
     * @mbg.generated
     */
    public Long getRonwo() {
        return ronwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column worker.ronwo
     *
     * @param ronwo the value for worker.ronwo
     *
     * @mbg.generated
     */
    public void setRonwo(Long ronwo) {
        this.ronwo = ronwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Worker other = (Worker) that;
        return (this.getWorker() == null ? other.getWorker() == null : this.getWorker().equals(other.getWorker()))
            && (this.getRonwo() == null ? other.getRonwo() == null : this.getRonwo().equals(other.getRonwo()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table worker
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getWorker() == null) ? 0 : getWorker().hashCode());
        result = prime * result + ((getRonwo() == null) ? 0 : getRonwo().hashCode());
        return result;
    }
}